# Usa una imagen ligera de Node.js
FROM node:18-alpine

# Directorio de trabajo
WORKDIR /app

# Copia archivos de dependencias
COPY package.json package-lock.json ./

# Instala dependencias (incluye Angular CLI)
RUN npm install

# Copia todo el proyecto
COPY . .

# Puerto de desarrollo de Angular
EXPOSE 4200

# Inicia la aplicación en modo desarrollo
CMD ["npm", "start"]