# Usa Node.js como base
FROM node:18-alpine

# Directorio de trabajo
WORKDIR /app

# Copia solo los archivos de dependencias
COPY package*.json ./

# Instala dependencias (Angular CLI debe estar listado en devDependencies o global)
RUN npm install

# Copia el resto del código
COPY . .

# Expone el puerto que usa Angular
EXPOSE 4200

# Comando para desarrollo (npm start debería correr ng serve)
CMD ["npm", "start"]
